language: java

env:
  global:
    - SONATYPE_USERNAME=ph@phloc.com
    - secure: "scgJRu0r6n84VxiTUZlL3/M0/usbkOJT2QJ84zPhpLx7jBIqOHJ17BxYl72ceyVuVSJJ1X5J1MKPbUJmiNOxw2nyj
+5oHC3j74EPhLKsF/o57AUY3HDJCXpEwBVkLCYmxgV24fnY8EH8WagEWuzqTxVuZMHm7e1DLkgD+IXXVhMEfghLVKrgDPsyVN0KY
X1OFRL98+KYTl9ULc12vTUskXvA7TdropFKs7YDz9DmJK26bNN783M8v4KbIyhWFXbpvteieXLrogVx25r3cDUHkf8SuvoOnFJGW
hCzkhPNlzDGH42D0a17/u6EDve5Vxrtr+2aPoQmcF8zfN4edmi3KK79I5agwKQNv/OsnenIFtnOqAt7E2OTyi+TmbcKk2oRyfVTU
VCNywsSCIs731Ukc1zZAxMC/Jz8/DQeWhyyOv5B2bZry8GMa0HwkeugMfoM84ISJeHs72P165KBBz2Tz0BpopzMAHpCpmnG/2vN2
IXE60/rHxd8Sz4zu1F+bSFKspw2fhAr79GLThY6uEVCfDDtyKddqMw3HJq9K5DxUlhSfJwB1osABpCWtkuyn7woWlcj6Xn0aQf/e
rAGjQ7tMLSQvxD3oqz4ymOJ8cpRAKFlxts0KCqSGfroqAqcbJ08+0aWJTCkwKOiBL0E5zXC2N6LTelSTtwK4uZ7z4kZsi4="

jdk:
  - oraclejdk8
  - oraclejdk11
  - openjdk11
  
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -U -P jdeps

script:
  - mvn test -B -P coverage
  
cache:
  directories:
    - $HOME/.m2

after_success:
  - mvn deploy --settings travis-settings.xml -DskipTests=true -B -P travis-deploy
  - bash <(curl -s https://codecov.io/bash)
  